# $Id$

RELPATH=	../../../..
SRCTOP=	${.CURDIR}/${RELPATH}

TS_SRCS=	dwarf_die_query.c
TS_DATA=	dt32-g1 dt64-g1 ec32-g1 ec64-g1 dto64-g1 ld_symver.o-64-g1

.include "${SRCTOP}/mk/elftoolchain.tet.mk"
