# $Id$

RELPATH=	../../../..
SRCTOP=	${.CURDIR}/${RELPATH}

TS_SRCS=	phdr.m4
TS_DATA=	ehdr.lsb64 ehdr.msb64 \
		phdr.lsb32 phdr.msb32 phdr.msb64 phdr.lsb64

.include "${SRCTOP}/mk/elftoolchain.tet.mk"
