# $Id$

RELPATH=	../../../..
SRCTOP=	${.CURDIR}/${RELPATH}

TS_SRCS=	phdr.m4
TS_DATA=	ehdr.msb32 ehdr.lsb32 \
		phdr.msb32 phdr.lsb32 phdr.msb64 phdr.lsb64

.include "${SRCTOP}/mk/elftoolchain.tet.mk"
