# $Id$

RELPATH=	../../../..
SRCTOP=	${.CURDIR}/${RELPATH}

TS_SRCS=	ehdr.m4
TS_DATA=	ehdr.msb64 ehdr.lsb64 ehdr.msb32 ehdr.lsb32 \
		newehdr.lsb64 newehdr.msb64

.include "${SRCTOP}/mk/elftoolchain.tet.mk"
