# $Id$

.include "${SRCTOP}/mk/elftoolchain.os.mk"

# libdwarf test suite uses libdwarf in /usr/local (i.e. SGI libdwarf),
# if TCGEN is defined.
.if defined(TCGEN)
DWARF_INC?=	/usr/local/include
DWARF_LIBS?=	/usr/local/lib
CFLAGS+=	-DTCGEN -I${DWARF_INC}
LDADD+=		-L${DWARF_LIBS}
.endif
LDADD+=		-ldwarf

DPADD+=		${LIBELF}
LDADD+=		-lelf

# Determine the location of the XML handling library.
.if ${OS_HOST} == FreeBSD
LDADD+=		-lbsdxml
.else
.if ${OS_HOST} == DragonFly || ${OS_HOST} == NetBSD
CFLAGS+=	-I/usr/pkg/include
LDADD+=		-L/usr/pkg/lib
.endif
LDADD+=		-lexpat
.endif

.if !defined(TCGEN)
.PATH:	${.OBJDIR}

TS_SRCS+=	ic_count.c
CLEANFILES+=	ic_count.c

ic_count.c:
	${TS_ROOT}/bin/count-ic ${.OBJDIR}
.endif

.for f in ${TS_DATA}
CLEANFILES+=	${f}.xml
.endfor

# Copy test objects(binaries) to the build directory uncompressed.
.for f in ${TS_DATA}
${f}: ${.CURDIR}/../common/object/${f}.gz
	gzcat ${.ALLSRC} > ${f}
.endfor

# NetBSD turns on -Wstrict-prototypes for WARNS>0; however
# TET 3.8's headers do not compile with -Wstrict-prototypes.
.if ${OS_HOST} != NetBSD
WARNS?=		2
.endif

# Test cases do not have manual pages.
NOMAN=		noman
